Fix intentional breakage.
Helpfully GitHub's CI now reports failures in a useful way.
See: https://github.com/daniel-levin/wild-test-files/actions/runs/18339596395/job/52231686219

```
running 1 test
test selftest ... FAILED

failures:

---- selftest stdout ----
Error: Expecting but cannot find artifact "gnu/crt1.o"

Caused by:
    No such file or directory (os error 2)
```